use capstone;
DROP TABLE IF EXISTS `exchangerate`;
CREATE TABLE `exchangerate` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RATE` decimal(10,6) DEFAULT NULL,
  `DATE` datetime NOT NULL,
  `TYPE` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`ID`), 
  CONSTRAINT date_unique UNIQUE (`DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `product`;
CREATE TABLE `product` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `USURL` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `CHURL` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `WIDTH` decimal(10,2) DEFAULT NULL,
  `HEIGHT` decimal(10, 2) DEFAULT NULL,
  `DEPTH` decimal(10, 2) DEFAULT NULL,
  `WEIGHT` decimal(10, 2) DEFAULT NULL,
  PRIMARY KEY(`ID`),
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `price`;
CREATE TABLE `price` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRODUCTID` bigint(20) NOT NULL,
  `USPRICE` decimal(10, 2) DEFAULT NULL,
  `CHPRICE` decimal(10, 2) DEFAULT NULL,
  `DATE` datetime NOT NULL,
  PRIMARY KEY(`ID`),
  KEY `IDX_PRICE_PRODUCT` (`PRODUCTID`),
  CONSTRAINT `PRICE_PRODUCT_FK1` FOREIGN KEY (`PRODUCTID`) REFERENCES `product` (`ID`),
  CONSTRAINT date_unique UNIQUE (`DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;